name: Integración Continua Práctica IV

on:
  push:
    branches: [ "main", "master" ]

jobs:
  construir-y-probar:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el código
      uses: actions/checkout@v4

    - name: Instalar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar pruebas
      run: mvn clean test
